#!/usr/bin/env node
/**
 * SPDX-FileCopyrightText: 2026 Christian Peter Kaiser
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { writeFileSync } from 'node:fs';
import { CipherEngine } from '../web/js/cipher-engine.js';
import { modernV3EncryptPayload, utf8ToBase26v2 } from '../web/js/modern-v3.js';

const DAY = {
  rotorThin: 'Beta',
  rotorLeft: 'V',
  rotorMiddle: 'VI',
  rotorRight: 'VIII',
  ringCode: 'EPEL',
  ringThin: 'E',
  ringLeft: 'P',
  ringMiddle: 'E',
  ringRight: 'L',
  plugboard: 'AE BF CM DQ HU JN LX PR SZ VW',
  endwalzeWiring: 'QWERTYUIOPASDFGHJKLZXCVBNM',
  notches: { left: 'AFLRX', middle: 'BEIMQUY', right: 'CDHKNPSVZ' },
  networkContext: 'ALB',
  epoch: '2026-08-16',
  groundKey: 'CDSZ',
};

function configureV3(engine, key) {
  const p = [...key];
  engine.setCryptoMode('modern');
  engine.setModernProtocol('v3');
  engine.setRotors('V', 'VI', 'VIII', 'Beta', p[1], p[2], p[3], p[0], 'P', 'E', 'L');
  engine.setThinRing('E');
  engine.setPlugboard(DAY.plugboard);
  engine.setEndwalze(DAY.endwalzeWiring);
  engine.setLueckenfuellerNotches(DAY.notches);
  return true;
}

const engine = new CipherEngine();
const plains = ['', 'A', 'Hello', 'Guten Tag! Äpfel 🔐', 'XXXXHELLOALBERICHYYYY'];
const vectors = [];

for (const [i, plain] of plains.entries()) {
  const enc = await modernV3EncryptPayload({
    engine,
    configure: (key) => configureV3(engine, key),
    groundKey: DAY.groundKey,
    plainText: plain,
    messageKey: 'LDNQ',
    messageId: 'TESTMSGX',
    dayConfig: DAY,
  });
  if (!enc.ok) throw new Error(enc.error);
  vectors.push({
    name: `v3-${i}-${plain.slice(0, 12) || 'empty'}`,
    kind: 'v3-roundtrip',
    day: DAY,
    plain,
    messageKey: 'LDNQ',
    messageId: 'TESTMSGX',
    cipher: enc.cipher,
    base26v2: utf8ToBase26v2(plain),
  });
}

vectors.push({
  name: 'base26v2-hello',
  kind: 'base26v2',
  plain: 'Hello',
  letters: utf8ToBase26v2('Hello'),
});
vectors.push({
  name: 'base26v2-umlaut',
  kind: 'base26v2',
  plain: 'Äpfel 🔐',
  letters: utf8ToBase26v2('Äpfel 🔐'),
});

{
  const trad = new CipherEngine();
  trad.setCryptoMode('traditional');
  trad.setReflector('C');
  trad.setRotors('V', 'VI', 'VIII', 'Beta', 'D', 'S', 'Z', 'C', 'P', 'E', 'L', DAY.ringThin);
  trad.setThinRing(DAY.ringThin);
  trad.setPlugboard(DAY.plugboard);
  const plain = 'HELLOALBERICHTESTMESSAGE';
  const cipher = trad.encryptMessage(plain);
  vectors.push({
    name: 'traditional-hello',
    kind: 'traditional',
    reflectorId: 'C',
    plugboard: DAY.plugboard,
    rotors: {
      left: 'V',
      middle: 'VI',
      right: 'VIII',
      thin: 'Beta',
      pos_l: 'D',
      pos_m: 'S',
      pos_r: 'Z',
      pos_t: 'C',
      ring_l: 'P',
      ring_m: 'E',
      ring_r: 'L',
      ring_t: DAY.ringThin,
    },
    plain,
    cipher,
  });
}

const out = {
  generatedAt: new Date().toISOString(),
  note: 'Generated by Web JS. Python reference and companion must match.',
  vectors,
};

const path = new URL('./golden-vectors.json', import.meta.url);
writeFileSync(path, `${JSON.stringify(out, null, 2)}\n`);
console.log('wrote', path.pathname, 'vectors', vectors.length);
